Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/Documentation:
  Enabled: false

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/SignalException:
  EnforcedStyle: only_raise

Lint/AmbiguousOperator:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false
